In [82]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [53]:
df=pd.read_csv(r"../../dataset/restaurant.csv")
df.dropna()
df.isnull().sum()
df

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,Naml۱ Gurme,208,��stanbul,"Kemanke�� Karamustafa Pa��a Mahallesi, R۱ht۱m ...",Karak�_y,"Karak�_y, ��stanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz A��ac۱,208,��stanbul,"Ko��uyolu Mahallesi, Muhittin ��st�_nda�� Cadd...",Ko��uyolu,"Ko��uyolu, ��stanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,A���k Kahve,208,��stanbul,"Kuru�_e��me Mahallesi, Muallim Naci Caddesi, N...",Kuru�_e��me,"Kuru�_e��me, ��stanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,��stanbul,"Cafea��a Mahallesi, Bademalt۱ Sokak, No 21/B, ...",Moda,"Moda, ��stanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [16]:
CategoricalColumns=df.select_dtypes(include="object").columns
CategoricalColumns

Index(['Restaurant Name', 'City', 'Address', 'Locality', 'Locality Verbose',
       'Cuisines', 'Currency', 'Has Table booking', 'Has Online delivery',
       'Is delivering now', 'Switch to order menu', 'Rating color',
       'Rating text'],
      dtype='object')

In [72]:
l= LabelEncoder()
df["Has Table booking"]=l.fit_transform(df["Has Table booking"])
df["Has Online delivery"]=l.fit_transform(df["Has Online delivery"])
df[["Has Table booking","Has Online delivery"]].head()

   Has Table booking  Has Online delivery
0                  1                    0
1                  1                    0
2                  1                    0
3                  0                    0
4                  1                    0

In [73]:
df[df["Cuisines"]=="North Indian"].head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
626,3400005,Time2Eat - Mama Chicken,1,Agra,"Main Market, Sadar Bazaar, Agra Cantt, Agra",Agra Cantt,"Agra Cantt, Agra",78.011608,27.160832,North Indian,...,Indian Rupees(Rs.),0,0,No,No,2,3.6,Yellow,Good,94
680,2400052,Eat On,1,Allahabad,"Palace Compound, Near Palace Cinema, MG Marg, ...",Civil Lines,"Civil Lines, Allahabad",81.834236,25.450377,North Indian,...,Indian Rupees(Rs.),0,0,No,No,1,3.7,Yellow,Good,105
686,2200078,Charming Chicken,1,Amritsar,"Shop 3, Opposite Nari Nikaten, Majithia Road, ...",Basant Nagar,"Basant Nagar, Amritsar",74.884384,31.644532,North Indian,...,Indian Rupees(Rs.),0,0,No,No,1,3.9,Yellow,Good,151
690,2200067,Bubby Fish & Chicken Corner,1,Amritsar,"Near Crystal Chowk, Cooper Road, INA Colony, A...",INA Colony,"INA Colony, Amritsar",74.875828,31.635671,North Indian,...,Indian Rupees(Rs.),0,0,No,No,1,3.5,Yellow,Good,91
699,2200132,Brothers Dhaba,1,Amritsar,"Golden Temple Out Road, Opposite Amritsar Muni...",Town Hall,"Town Hall, Amritsar",74.877666,31.625981,North Indian,...,Indian Rupees(Rs.),0,0,No,No,2,3.8,Yellow,Good,276

In [64]:
print(df["Cuisines"].value_counts())

Cuisines
North Indian                          936
North Indian, Chinese                 511
Chinese                               354
Fast Food                             354
North Indian, Mughlai                 334
                                     ...
World Cuisine, Patisserie, Cafe         1
Burger, Izgara                          1
Desserts, B�_rek                        1
Restaurant Cafe, Turkish, Desserts      1
Restaurant Cafe, Desserts               1
Name: count, Length: 1825, dtype: int64

In [80]:
df.drop(columns=["Restaurant ID","Restaurant Name","Address","Locality","Locality Verbose"],inplace=True)

In [81]:
df.head()

,Country Code,City,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,162,Makati City,121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),1,0,No,No,3,4.8,Dark Green,Excellent,314
1,162,Makati City,121.014101,14.553708,Japanese,1200,Botswana Pula(P),1,0,No,No,3,4.5,Dark Green,Excellent,591
2,162,Mandaluyong City,121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),1,0,No,No,4,4.4,Green,Very Good,270
3,162,Mandaluyong City,121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),0,0,No,No,4,4.9,Dark Green,Excellent,365
4,162,Mandaluyong City,121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),1,0,No,No,4,4.8,Dark Green,Excellent,229

In [128]:
df.to_csv("../../dataset/restaurant_cleaned.csv", index=False)

In [129]:
O = OneHotEncoder(sparse_output=False)
new = O.fit_transform(df[["Cuisines"]])
new_df=pd.DataFrame(
    new,
    columns=O.get_feature_names_out(["Cuisines"])
)
new_df=df["Cuisines"].str.get_dummies(sep=",")
df=pd.concat([df,new_df],axis=1)
df.drop("Cuisines",axis=1,inplace=True)

KeyError: "None of [Index(['Cuisines'], dtype='object')] are in the [columns]"

In [116]:
print(df.columns[df.columns.duplicated()])

Index([' Afghani', ' African', ' American', ' Andhra', ' Arabian',
       ' Argentine', ' Armenian', ' Asian', ' Assamese', ' Australian',
       ...
       'Tapas', 'Tea', 'Tex-Mex', 'Thai', 'Tibetan', 'Turkish',
       'Turkish Pizza', 'Vietnamese', 'Western', 'World Cuisine'],
      dtype='object', length=249)

In [117]:
print(df.columns.duplicated().sum())

249

In [118]:
df = df.loc[:, ~df.columns.duplicated()]

In [119]:
print(df.columns[df.columns.duplicated()])

Index([], dtype='object')

In [124]:
df[df["World Cuisine"] == 1].head(51)

,Country Code,City,Longitude,Latitude,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,...,Tapas,Tea,Tex-Mex,Thai,Tibetan,Turkish,Turkish Pizza,Vietnamese,Western,World Cuisine
9524,208,Ankara,32.869800,39.898239,80,Turkish Lira(TL),0,0,No,No,...,0,0,0,0,0,0,0,0,0,1
9525,208,Ankara,32.865683,39.897872,150,Turkish Lira(TL),0,0,No,No,...,0,0,0,0,0,0,0,0,0,1
9547,208,��stanbul,29.041297,41.009847,105,Turkish Lira(TL),0,0,No,No,...,0,0,0,0,0,0,0,0,0,1